### ISSUE TITLE
Has this been discontinued?

### ISSUE THREAD

**Issue by dajix350** [kiwibrowser/sync#2]

**Comment by Cyberavater** [comment]
@d3ward I don't see the crx file, How do I install it?

**Comment by Cyberavater** [comment]
Okay, download as zip works but I don't see my bookmark getting sync.

**Comment by dajix350** [comment]
That still doesn't answer my question. Is this project still supported and/or being developed?

**Comment by d3ward** [comment]
This extension is technically discontinued , maybe in future will have an active development.
For now we suggest to take a look at other solutions like [Floccus](https://floccus.org/)
