### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tathastu871** [kiwibrowser/sync#3]
First of all i used to have 4 browsers on android each with different functionalities. Now i have replaced all with kiwi. Since Kiwi has extreme number of features and ui Customizations.

The only features still lacking is:

Syncing Bookmark; History; Opened tab list ---> No need to buy and maintain public storage servers for storing user bookmarks and data. Instead just **integrate the kiwi android with users** **google drive** so that continuously the user data is backup up to google drive. (Note: It is needed because suddenly if we have to uninstall app or format phone and we forgot to export the bookmarks we will have a massive data loss, however if bookmarks are continously backed up to users drive it will be helpful).

Another feature require is the ability to reload all the tabs and export list of open tabs to text file. Suppose we have 1000 tabs open and we have to remove app or format phone we can export and import the list of open tabs and thus restore them. Currently there are extensions that export list of open tabs but if we have 1000 tabs open and close the app and restart it only last tab is reloaded and extension can detect only one open tab not all.But if it has inbuilt functionality to export list of all open tabs its greatly useful.

Just by adding above two features kiwi will be the ultimate and complete browser on android platform

If users data is synced backed up in users on google drive instead of public storage server it will maintain user's privacy and also prevent the developer of this app need to pay for storage servers

**Comment by jackyzy823** [comment]
> Currently there are extensions that export list of open tabs but if we have 1000 tabs open and close the app and restart it only last tab is reloaded and extension can detect only one open tab not all.But if it has inbuilt functionality to export list of all open tabs its greatly useful.

I have exactly the same issue with you. I have a lot of opening tabs ,  then when i want to bookmark all with help of extensions , i found no one will show the entire opening tabs. 



> If users data is synced backed up in users on google drive instead of public storage server it will maintain user's privacy and also prevent the developer of this app need to pay for storage servers

I have an idea that we can make [sync server](https://github.com/brave/go-sync ) like `brave` does .

Kiwi can implement and host a sync server and provide to user as premium feature  to cover  servers' billing (and make a instruction for users to self host a sync server)

Users can choose to self host their own sync server and configure server and auth info in kiwi browser's setting.

**Comment by tathastu871** [comment]
But why paid servers integrate it with google drive. Of atleast add some code to internally extract list of opened tabs as txt and export. since without root we cannot access internal files of app like tabs bookmarks. And 1 in 100 have rooted device


Plus brave browser is the worst ever browser worst bookmark manager worst app keeps crashing on brave i lost much data due to above issues. as complete reinstall is only way to make brave work again.

**Comment by tathastu871** [comment]
> > Currently there are extensions that export list of open tabs but if we have 1000 tabs open and close the app and restart it only last tab is reloaded and extension can detect only one open tab not all.But if it has inbuilt functionality to export list of all open tabs its greatly useful.
> 
> I have exactly the same issue with you. I have a lot of opening tabs , then when i want to bookmark all with help of extensions , i found no one will show the entire opening tabs.
> 
> > If users data is synced backed up in users on google drive instead of public storage server it will maintain user's privacy and also prevent the developer of this app need to pay for storage servers
> 
> I have an idea that we can make [sync server](https://github.com/brave/go-sync) like `brave` does .
> 
> Kiwi can implement and host a sync server and provide to user as premium feature to cover servers' billing (and make a instruction for users to self host a sync server)
> 
> Users can choose to self host their own sync server and configure server and auth info in kiwi browser's setting.

Dont try to emulate brave its the worst ever browser. Thats the reason i tried switching to kiwi from brave
