### ISSUE TITLE
Sync with Google Chrome

### ISSUE THREAD

**Issue by vldanch** [kiwibrowser/sync#4]
Good afternoon, tell me how you can synchronize with chrome.
Put the zip archive as an extension in the browser on the computer and on kiwi on the android.
Entered the key that issued the plug-in from the computer to the smartphone, but the synchronization did not occur.
Maybe I'm doing something wrong?

**Comment by yotiko** [comment]
Same problem here

**Comment by vldanch** [comment]
@yotiko Did you manage to overcome this problem?

@kiwibrowser Will there be a fix for this situation?

**Comment by yotiko** [comment]
Nope. Just removed it.

**Comment by smabdulmueid97** [comment]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
{
  "name": "Kiwi Sync",
  "version": "1.0",
  "description": "Kiwi Sync is an extension to synchronize your bookmarks and profile across your browsers (including Kiwi Browser)",
  "background": {
    "scripts": ["firebase-app.js", "firebase-auth.js", "firebase-firestore.js", "toolbox.js", "crypto.js", "background.js"],
    "persistent": true
  },
  "browser_action": {
    "default_icon": "img/icon32.png",
    "default_popup": "popup.html"
  },
  "options_page": "options.html",
  "icons": {
    "16": "img/icon16.png",
    "48": "img/icon48.png",
    "128": "img/icon128.png"
  },
  "minimum_chrome_version": "9",
  "commands": {
    "_execute_browser_action": {
      "suggested_key": {
        "default": "Ctrl+Shift+F",
        "mac": "MacCtrl+F"
      }
    }
  },
  "permissions": ["bookmarks", "tabs"],
  "manifest_version": 2
}

**Comment by StacktraceException** [comment]
I have tried to sync today with Edge and Opera on desktop and Kiwi on mobile. I have copied and pasted the code appropriately but nothing happens.

Please consider upgrading/fixing.

**Comment by bremaya** [comment]
When will we have this extension updated?  Please implement this function with other browsers, or at least the chromium family...

**Comment by vonDubenshire** [comment]
I'm also intrigued if anyone here or any other projects have managed to successfully get a sync working anywhere.

**Comment by d3ward** [comment]
@vonDubenshire this project is not maintained anymore , better use a solution like https://floccus.org/ which works with Kiwi and any other browser on desktop
