### ISSUE TITLE
I really need help, i need to reset my phone, but I have either 773 tabs or 773 sessions saved in kiwi(NOT bookmarks) I only have 5 bookmarks.

### ISSUE THREAD

**Issue by Username23453** [kiwibrowser/sync#5]
And I need to transfer the 773 to my desktop somehow, so i can review them there. I know about floccus, but its asking whether I want to use WebDAV, i dont know how to use that, & also its asking if i want to use my google drive. I was about to try this. But, i'm concerned on how this would work. I have desktop browser profiles connected to my google drive account, with saved history,sessions, bookmarks, & I'm concerned floccus might delete my kiwi stuff & move my desktop browser profile data to my kiwi browser. I need some help, urgently, a walkthrough or something. My phone is lagging extremely & serious other problems & I urgently need to reset the OS.
I've also tried "Kiwi Sync" extension, but it didnt work at all.
-Thank you.

**Comment by d3ward** [comment]
Hi , sync project is very outdated and likely discontinued . 
If you want you can try with a solution like https://github.com/Karna98/Save-Tabs . Last time I tried it I had around 100 tabs and it worked . In order to make it work you probably need to reactivate tabs by going to them 1 by one ..

**Comment by Username23453** [comment]
@d3ward , thanks, I appreciate it, unfortunately, that would take extremely long time with over 700 sessions or tabs.

**Comment by Username23453** [comment]
@d3ward , when i refresh certain tabs in order to transfer them, the domain resets & erases the URL. Could you help me to transfer my kiwibrowser tabs, via the adb method, i have a linux PC too. Also it would take forever to transfer 700 tabs, here is my recent post:
https://stackoverflow.com/questions/76455051/i-need-help-accessing-kiwibrowser-sessions-tabs-on-my-android-transfering-them

**Comment by d3ward** [comment]
You could try this ( for me it worked ). Connect your phone to a computer . Using a chrome based browser go to "chrome://inspect/#devices" , it's required to have adb enabled on the smartphone . From that page you should be able to see all the tabs of Kiwi . Now open devtools on the "chrome://inspect/#devices" , go to the console and paste this code 
```
const elements = document.querySelectorAll(".list.pages .url");
const urls = Array.from(elements).map(element => element.textContent);
console.log(urls);
```
You should now have an array of urls, which you can do anything you want with scripting ( open all url , convert them to bookmarks etc.) 
Let me know

**Comment by Username23453** [comment]
@d3ward , thank you so much, this worked beautifully. ALL 700 tabs showed up :D :O  I cant believe it. thank goodness. Now I have them all backed up on my PC & i can reset/reformat my slow phone now. Hopefully I dont have any rootkits on my phone that a reformat wont remove. 

I was posting everywhere, in reddit, stackoverflow, etc asking for help. Also, this almost didnt work, at least not initially,  because i didnt know while doing this that i needed to have kiwibrowser open on my android. So when i 1st tried it, it didnt work. 
Is there any way i can compensate you or tip you for the help?

**Comment by Username23453** [comment]
@d3ward , ok, so now i'm going to try to do similar to "Styx browser" https://github.com/jamal2362/Styx

 & DuckDuckgo browser for android, but ur method isnt working. Any idea on how to do this with styx & duckduckgo? I will ask on their github myself also.

**Comment by d3ward** [comment]
Glad it worked! No need to compensate .  already means a lot that you use Kiwi , my projects and let others know about it !

About styx , it's possible it doesn't work because doesn't use chromium . The above trick works only with chromium based browsers . For styx , I wish you to find a solution , probably the dev of it knows better
